name: clup_management
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '3.5.3'
dependencies:
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.3.2
  sqflite: ^2.4.0
  csv: any
  intl: any
  path_provider: ^2.0.15
  path: ^1.9.0
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.1.0
  animated_background: ^2.0.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/splash.jpg
    - images/desc.jpg
    - images/desc1.jpg
    - images/desc2.jpg
    - images/desc3.jpg
    - images/back.jpg
    - images/arm.jpg
    - images/leg.jpg
    - images/beg.jpg
    - images/chest.jpg
    - images/second.jpg
  #   - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
